Ejercicio 1
MatiasCarrara/Induccion_anima pull request #1
Opened 2017-11-14 20:53 UTC by MatiasCarrara

2017-12-19 13:41 UTC, lcarozzi requested changes

2017-12-19 13:41 UTC, lcarozzi commented on ej1.rb
> +  attr_accessor :folk
cambiar nombre al atributo

2017-12-19 13:41 UTC, lcarozzi commented on ej1.rb
> +# ej1.rb
borrar

2017-12-19 13:41 UTC, lcarozzi commented on ej1.rb
> +  def tell
cambiar nombre al metodo

2017-12-19 13:41 UTC, lcarozzi commented on ej1.rb
> +    return 'Hi' unless @folk.respond_to?('length')
y esto?

2017-12-19 13:41 UTC, lcarozzi commented on ej1.rb
> +    this = @folk
usar variables con nombres mas significativos

2017-12-19 13:41 UTC, lcarozzi commented on ej1.rb
> +      @folk.each do |var|
usar nombres de variables mas significativos

2017-12-19 13:41 UTC, lcarozzi commented on ej1.rb
> +      this = @folk[0]
usar metodo .first

2017-12-19 13:41 UTC, lcarozzi commented on ej1.rb
> +    this.to_s
innecesario el .to_s

2017-12-19 13:41 UTC, lcarozzi commented on spec/ej1_spec.rb
> +require '/home/mooveit/MyGit/Induccion_anima/ej1.rb'
usar require relative

2017-12-19 13:41 UTC, lcarozzi commented on spec/ej1_spec.rb
> +# spec/ej1_spec.rb
borrar

2017-12-19 13:41 UTC, lcarozzi commented on spec/ej1_spec.rb
> +  #  o=Long.new
borrar

2017-12-19 13:41 UTC, lcarozzi commented on spec/ej1_spec.rb
> +        expect(Long.new(%w[Matias Valentina]).tell).to eql('Valentina')
usar eq en lugar de eql

2017-12-19 13:41 UTC, lcarozzi commented on spec/ej1_spec.rb
> +  describe '.tell' do
usar subject y let para parametros
preguntar a cris

2017-12-26 11:53 UTC, cdotta requested changes

2017-12-26 11:53 UTC, cdotta commented on README.md
> +######`def initialize(size)`
la idea no es explicar detalles de implementación aca. La idea del readme es explicar que hace y como lo uso yo que no se nada de tu código.

2017-12-26 11:53 UTC, cdotta commented on ej1.rb
> +  def to_size
`to_size` no es un buen nombre, que te parece `biggest`? o `longest`?

2017-12-26 11:53 UTC, cdotta commented on ej1.rb
> +    if @size.respond_to?('each')
este if no es necesario. Asumí que responde a `each`

2017-12-26 11:53 UTC, cdotta commented on ej1.rb
> +    this = @size
porque le pusiste `this` a la variable? no dice mucho acerca de que se guarda en ella

2017-12-26 11:53 UTC, cdotta commented on spec/ej1_spec.rb
> +describe Long do
estoy 100% seguro de que estos test no funcionan

2017-12-26 11:53 UTC, cdotta commented on ej1.rb
> +    @size = size
size no es un buen nombre, trata de usar nombres que sean fáciles de entender para quien lee el método.

2017-12-26 11:53 UTC, cdotta commented on ej1.rb
> +  attr_accessor :size
para que necesitas este `attr_accessor`?

2017-12-26 13:20 UTC, lcarozzi requested changes

2017-12-26 13:20 UTC, lcarozzi commented on ej1.rb
> +Exercise1.biggest(%w[Matias Valentina])
estas llamando al metodo

2017-12-26 13:20 UTC, lcarozzi commented on ej1.rb
> +  puts longest
porque `puts`?

2017-12-26 13:20 UTC, lcarozzi commented on ej1.rb
> +    @data = data
porque usas `@data` ? podes usar el data de los parametros

2017-12-26 13:20 UTC, lcarozzi commented on spec/ej1_spec.rb
> +require_relative '/Users/matiascarrara/Git/Induccion_anima/ej1.rb'
cambiar

2017-12-26 13:20 UTC, lcarozzi commented on spec/ej1_spec.rb
> +        expect(Exercise1.biggest(['hola'])).to eql(puts('hola'))
esto no tiene sentido. el metodo biggest imprime el string mas largo, pero por como esta implementado retorna `nil`. este `expect` en realdiad esta comparado nil con nil.

2017-12-27 13:25 UTC, lcarozzi requested changes

2017-12-27 13:25 UTC, lcarozzi commented on ej1.rb
> +      var.length > longest.length ? longest = var : longest
pensa si es necesario el else

2017-12-27 13:25 UTC, lcarozzi commented on spec/ej1_spec.rb
> +    context 'Single word' do
usar `subject` y `let` (preguntar a valentina)

2017-12-27 13:25 UTC, lcarozzi commented on spec/ej1_spec.rb
> +    context 'Single word' do
usar `eq` en lugar de `eql`

2018-01-02 13:24 UTC, lcarozzi requested changes

2018-01-02 13:24 UTC, lcarozzi commented on spec/ej1_spec.rb
> +    context do
agregar descripcion en los contexts

2018-01-02 13:24 UTC, lcarozzi commented on spec/ej1_spec.rb
> +require_relative '../ej1.rb'
esta todo mal indentado

2018-01-02 13:24 UTC, lcarozzi commented on spec/ej1_spec.rb
> +end
corriste rubocop?

2018-01-09 13:28 UTC, lcarozzi approved these changes

2018-01-09 13:40 UTC, merged