Ejercicio 2
MatiasCarrara/Induccion_anima pull request #2
Opened 2017-11-15 19:45 UTC by MatiasCarrara

2017-12-19 13:42 UTC, lcarozzi requested changes

2017-12-19 13:42 UTC, lcarozzi commented on ej2.rb
> +    num = rand(10.00...100.00)
intenta hacer todo en una linea, asi no usas variables de forma innecesaria

2017-12-19 13:42 UTC, lcarozzi commented on spec/ej2_spec.rb
> +require '/home/mooveit/MyGit/Induccion_anima/ej2.rb'
cambiar

2017-12-19 13:42 UTC, lcarozzi commented on spec/ej2_spec.rb
> +# spec/ej2_spac.rb
borrar

2017-12-19 13:42 UTC, lcarozzi commented on spec/ej2_spec.rb
> +    context 'instance the module ' do
cambiar nombre al contexto o eliminarlo

2017-12-26 11:54 UTC, cdotta requested changes

2017-12-26 11:54 UTC, cdotta commented on ej2.rb
> +    num = rand(10.00...100.00).round(2)
para que necesitas la variable num? no se podría borrar?

2017-12-26 13:21 UTC, lcarozzi requested changes

2017-12-26 13:21 UTC, lcarozzi commented on spec/ej2_spec.rb
> +require_relative '/Users/matiascarrara/Git/Induccion_anima/ej2.rb'
cambiar

2017-12-27 13:25 UTC, lcarozzi approved these changes

2017-12-28 13:14 UTC, merged